(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite1 - satellite
	instrument8 - instrument
	satellite2 - satellite
	instrument9 - instrument
	instrument10 - instrument
	satellite3 - satellite
	instrument11 - instrument
	satellite4 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite5 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite6 - satellite
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite7 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	satellite8 - satellite
	instrument36 - instrument
	instrument37 - instrument
	satellite9 - satellite
	instrument38 - instrument
	instrument39 - instrument
	image0 - mode
	infrared2 - mode
	image3 - mode
	thermograph1 - mode
	spectrograph4 - mode
	GroundStation4 - direction
	Star6 - direction
	Star8 - direction
	GroundStation5 - direction
	GroundStation7 - direction
	Star3 - direction
	GroundStation2 - direction
	Star1 - direction
	Star9 - direction
	GroundStation0 - direction
	Star10 - direction
	Star11 - direction
)
(:init
	(supports instrument0 image3)
	(calibration_target instrument0 GroundStation0)
	(calibration_target instrument0 Star8)
	(calibration_target instrument0 GroundStation4)
	(supports instrument1 thermograph1)
	(calibration_target instrument1 Star3)
	(calibration_target instrument1 Star1)
	(calibration_target instrument1 Star6)
	(supports instrument2 spectrograph4)
	(supports instrument2 infrared2)
	(calibration_target instrument2 Star6)
	(supports instrument3 image0)
	(supports instrument3 image3)
	(supports instrument3 spectrograph4)
	(calibration_target instrument3 Star9)
	(supports instrument4 infrared2)
	(calibration_target instrument4 GroundStation4)
	(calibration_target instrument4 GroundStation2)
	(supports instrument5 spectrograph4)
	(calibration_target instrument5 Star6)
	(supports instrument6 infrared2)
	(supports instrument6 image3)
	(calibration_target instrument6 Star9)
	(calibration_target instrument6 GroundStation2)
	(calibration_target instrument6 Star8)
	(supports instrument7 spectrograph4)
	(supports instrument7 image3)
	(supports instrument7 infrared2)
	(calibration_target instrument7 GroundStation0)
	(calibration_target instrument7 GroundStation5)
	(calibration_target instrument7 Star1)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star3)
	(= (data_capacity satellite0) 1000)
	(= (fuel satellite0) 114)
	(supports instrument8 infrared2)
	(calibration_target instrument8 GroundStation5)
	(on_board instrument8 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star11)
	(= (data_capacity satellite1) 1000)
	(= (fuel satellite1) 179)
	(supports instrument9 spectrograph4)
	(supports instrument9 image3)
	(calibration_target instrument9 Star9)
	(supports instrument10 image3)
	(supports instrument10 infrared2)
	(calibration_target instrument10 Star3)
	(calibration_target instrument10 GroundStation7)
	(calibration_target instrument10 Star9)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star1)
	(= (data_capacity satellite2) 1000)
	(= (fuel satellite2) 182)
	(supports instrument11 image0)
	(supports instrument11 image3)
	(supports instrument11 spectrograph4)
	(calibration_target instrument11 GroundStation7)
	(calibration_target instrument11 GroundStation2)
	(on_board instrument11 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Star10)
	(= (data_capacity satellite3) 1000)
	(= (fuel satellite3) 190)
	(supports instrument12 image0)
	(supports instrument12 spectrograph4)
	(calibration_target instrument12 GroundStation2)
	(calibration_target instrument12 GroundStation0)
	(supports instrument13 image3)
	(supports instrument13 infrared2)
	(calibration_target instrument13 Star8)
	(calibration_target instrument13 Star1)
	(supports instrument14 image0)
	(supports instrument14 infrared2)
	(calibration_target instrument14 Star3)
	(supports instrument15 image0)
	(supports instrument15 infrared2)
	(supports instrument15 thermograph1)
	(calibration_target instrument15 GroundStation2)
	(calibration_target instrument15 Star3)
	(supports instrument16 image3)
	(supports instrument16 infrared2)
	(calibration_target instrument16 GroundStation5)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star1)
	(= (data_capacity satellite4) 1000)
	(= (fuel satellite4) 195)
	(supports instrument17 image3)
	(supports instrument17 infrared2)
	(calibration_target instrument17 GroundStation7)
	(calibration_target instrument17 GroundStation0)
	(calibration_target instrument17 GroundStation4)
	(supports instrument18 thermograph1)
	(supports instrument18 infrared2)
	(supports instrument18 spectrograph4)
	(calibration_target instrument18 GroundStation5)
	(calibration_target instrument18 GroundStation4)
	(calibration_target instrument18 GroundStation0)
	(supports instrument19 image3)
	(calibration_target instrument19 Star1)
	(calibration_target instrument19 Star9)
	(supports instrument20 image0)
	(calibration_target instrument20 GroundStation4)
	(calibration_target instrument20 Star9)
	(calibration_target instrument20 GroundStation7)
	(supports instrument21 spectrograph4)
	(supports instrument21 infrared2)
	(calibration_target instrument21 GroundStation7)
	(supports instrument22 thermograph1)
	(calibration_target instrument22 Star9)
	(supports instrument23 thermograph1)
	(calibration_target instrument23 GroundStation5)
	(calibration_target instrument23 Star9)
	(calibration_target instrument23 Star3)
	(supports instrument24 image3)
	(calibration_target instrument24 Star6)
	(calibration_target instrument24 GroundStation5)
	(supports instrument25 image3)
	(supports instrument25 image0)
	(calibration_target instrument25 GroundStation7)
	(calibration_target instrument25 Star8)
	(on_board instrument17 satellite5)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(on_board instrument20 satellite5)
	(on_board instrument21 satellite5)
	(on_board instrument22 satellite5)
	(on_board instrument23 satellite5)
	(on_board instrument24 satellite5)
	(on_board instrument25 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star3)
	(= (data_capacity satellite5) 1000)
	(= (fuel satellite5) 108)
	(supports instrument26 thermograph1)
	(supports instrument26 image0)
	(calibration_target instrument26 Star3)
	(supports instrument27 image0)
	(calibration_target instrument27 Star1)
	(supports instrument28 spectrograph4)
	(supports instrument28 image0)
	(supports instrument28 infrared2)
	(calibration_target instrument28 GroundStation4)
	(supports instrument29 image0)
	(calibration_target instrument29 GroundStation5)
	(calibration_target instrument29 Star6)
	(supports instrument30 infrared2)
	(supports instrument30 image3)
	(calibration_target instrument30 GroundStation2)
	(calibration_target instrument30 Star6)
	(calibration_target instrument30 GroundStation7)
	(supports instrument31 spectrograph4)
	(supports instrument31 infrared2)
	(supports instrument31 image0)
	(calibration_target instrument31 GroundStation0)
	(calibration_target instrument31 Star1)
	(supports instrument32 infrared2)
	(calibration_target instrument32 GroundStation5)
	(calibration_target instrument32 GroundStation2)
	(on_board instrument26 satellite6)
	(on_board instrument27 satellite6)
	(on_board instrument28 satellite6)
	(on_board instrument29 satellite6)
	(on_board instrument30 satellite6)
	(on_board instrument31 satellite6)
	(on_board instrument32 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star10)
	(= (data_capacity satellite6) 1000)
	(= (fuel satellite6) 164)
	(supports instrument33 infrared2)
	(supports instrument33 image3)
	(calibration_target instrument33 GroundStation7)
	(calibration_target instrument33 GroundStation2)
	(supports instrument34 thermograph1)
	(supports instrument34 infrared2)
	(supports instrument34 spectrograph4)
	(calibration_target instrument34 GroundStation2)
	(calibration_target instrument34 GroundStation5)
	(calibration_target instrument34 Star8)
	(supports instrument35 spectrograph4)
	(supports instrument35 infrared2)
	(supports instrument35 image3)
	(calibration_target instrument35 GroundStation2)
	(calibration_target instrument35 GroundStation7)
	(on_board instrument33 satellite7)
	(on_board instrument34 satellite7)
	(on_board instrument35 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star8)
	(= (data_capacity satellite7) 1000)
	(= (fuel satellite7) 105)
	(supports instrument36 image0)
	(supports instrument36 thermograph1)
	(calibration_target instrument36 GroundStation2)
	(calibration_target instrument36 Star3)
	(supports instrument37 image3)
	(supports instrument37 infrared2)
	(supports instrument37 spectrograph4)
	(calibration_target instrument37 Star9)
	(on_board instrument36 satellite8)
	(on_board instrument37 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star3)
	(= (data_capacity satellite8) 1000)
	(= (fuel satellite8) 134)
	(supports instrument38 thermograph1)
	(calibration_target instrument38 Star1)
	(supports instrument39 spectrograph4)
	(calibration_target instrument39 GroundStation0)
	(calibration_target instrument39 Star9)
	(on_board instrument38 satellite9)
	(on_board instrument39 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star10)
	(= (data_capacity satellite9) 1000)
	(= (fuel satellite9) 124)
	(= (data Star10 image0) 164)
	(= (data Star11 image0) 145)
	(= (data Star10 infrared2) 263)
	(= (data Star11 infrared2) 251)
	(= (data Star10 image3) 248)
	(= (data Star11 image3) 92)
	(= (data Star10 thermograph1) 15)
	(= (data Star11 thermograph1) 12)
	(= (data Star10 spectrograph4) 50)
	(= (data Star11 spectrograph4) 61)
	(= (slew_time GroundStation4 GroundStation0) 51.41)
	(= (slew_time GroundStation0 GroundStation4) 51.41)
	(= (slew_time GroundStation4 Star1) 38.57)
	(= (slew_time Star1 GroundStation4) 38.57)
	(= (slew_time GroundStation4 GroundStation2) 10.38)
	(= (slew_time GroundStation2 GroundStation4) 10.38)
	(= (slew_time GroundStation4 Star3) 46.38)
	(= (slew_time Star3 GroundStation4) 46.38)
	(= (slew_time Star6 GroundStation0) 53.15)
	(= (slew_time GroundStation0 Star6) 53.15)
	(= (slew_time Star6 Star1) 28.83)
	(= (slew_time Star1 Star6) 28.83)
	(= (slew_time Star6 GroundStation2) 6.459)
	(= (slew_time GroundStation2 Star6) 6.459)
	(= (slew_time Star6 Star3) 4.005)
	(= (slew_time Star3 Star6) 4.005)
	(= (slew_time Star6 GroundStation4) 24.88)
	(= (slew_time GroundStation4 Star6) 24.88)
	(= (slew_time Star6 GroundStation5) 12.59)
	(= (slew_time GroundStation5 Star6) 12.59)
	(= (slew_time Star8 GroundStation0) 47.34)
	(= (slew_time GroundStation0 Star8) 47.34)
	(= (slew_time Star8 Star1) 45.74)
	(= (slew_time Star1 Star8) 45.74)
	(= (slew_time Star8 GroundStation2) 75.61)
	(= (slew_time GroundStation2 Star8) 75.61)
	(= (slew_time Star8 Star3) 43.57)
	(= (slew_time Star3 Star8) 43.57)
	(= (slew_time Star8 GroundStation4) 56.46)
	(= (slew_time GroundStation4 Star8) 56.46)
	(= (slew_time Star8 GroundStation5) 57.52)
	(= (slew_time GroundStation5 Star8) 57.52)
	(= (slew_time Star8 Star6) 69.02)
	(= (slew_time Star6 Star8) 69.02)
	(= (slew_time Star8 GroundStation7) 55.29)
	(= (slew_time GroundStation7 Star8) 55.29)
	(= (slew_time GroundStation5 GroundStation0) 4.214)
	(= (slew_time GroundStation0 GroundStation5) 4.214)
	(= (slew_time GroundStation5 Star1) 50.43)
	(= (slew_time Star1 GroundStation5) 50.43)
	(= (slew_time GroundStation5 GroundStation2) 27.59)
	(= (slew_time GroundStation2 GroundStation5) 27.59)
	(= (slew_time GroundStation5 Star3) 16.88)
	(= (slew_time Star3 GroundStation5) 16.88)
	(= (slew_time GroundStation5 GroundStation4) 66.07)
	(= (slew_time GroundStation4 GroundStation5) 66.07)
	(= (slew_time GroundStation7 GroundStation0) 25.98)
	(= (slew_time GroundStation0 GroundStation7) 25.98)
	(= (slew_time GroundStation7 Star1) 51.08)
	(= (slew_time Star1 GroundStation7) 51.08)
	(= (slew_time GroundStation7 GroundStation2) 24.63)
	(= (slew_time GroundStation2 GroundStation7) 24.63)
	(= (slew_time GroundStation7 Star3) 69.64)
	(= (slew_time Star3 GroundStation7) 69.64)
	(= (slew_time GroundStation7 GroundStation4) 2.792)
	(= (slew_time GroundStation4 GroundStation7) 2.792)
	(= (slew_time GroundStation7 GroundStation5) 11.02)
	(= (slew_time GroundStation5 GroundStation7) 11.02)
	(= (slew_time GroundStation7 Star6) 13.41)
	(= (slew_time Star6 GroundStation7) 13.41)
	(= (slew_time Star3 GroundStation0) 31.79)
	(= (slew_time GroundStation0 Star3) 31.79)
	(= (slew_time Star3 Star1) 48.07)
	(= (slew_time Star1 Star3) 48.07)
	(= (slew_time Star3 GroundStation2) 44.1)
	(= (slew_time GroundStation2 Star3) 44.1)
	(= (slew_time GroundStation2 GroundStation0) 45.09)
	(= (slew_time GroundStation0 GroundStation2) 45.09)
	(= (slew_time GroundStation2 Star1) 19.1)
	(= (slew_time Star1 GroundStation2) 19.1)
	(= (slew_time Star1 GroundStation0) 35.4)
	(= (slew_time GroundStation0 Star1) 35.4)
	(= (slew_time Star9 GroundStation0) 26.3)
	(= (slew_time GroundStation0 Star9) 26.3)
	(= (slew_time Star9 Star1) 36.2)
	(= (slew_time Star1 Star9) 36.2)
	(= (slew_time Star9 GroundStation2) 12.53)
	(= (slew_time GroundStation2 Star9) 12.53)
	(= (slew_time Star9 Star3) 71.35)
	(= (slew_time Star3 Star9) 71.35)
	(= (slew_time Star9 GroundStation4) 52.66)
	(= (slew_time GroundStation4 Star9) 52.66)
	(= (slew_time Star9 GroundStation5) 65.46)
	(= (slew_time GroundStation5 Star9) 65.46)
	(= (slew_time Star9 Star6) 33.82)
	(= (slew_time Star6 Star9) 33.82)
	(= (slew_time Star9 GroundStation7) 13.41)
	(= (slew_time GroundStation7 Star9) 13.41)
	(= (slew_time Star9 Star8) 5.781)
	(= (slew_time Star8 Star9) 5.781)
	(= (slew_time Star10 GroundStation0) 68.79)
	(= (slew_time GroundStation0 Star10) 68.79)
	(= (slew_time Star10 Star1) 61.23)
	(= (slew_time Star1 Star10) 61.23)
	(= (slew_time Star10 GroundStation2) 30.77)
	(= (slew_time GroundStation2 Star10) 30.77)
	(= (slew_time Star10 Star3) 19.25)
	(= (slew_time Star3 Star10) 19.25)
	(= (slew_time Star10 GroundStation4) 63.68)
	(= (slew_time GroundStation4 Star10) 63.68)
	(= (slew_time Star10 GroundStation5) 52.02)
	(= (slew_time GroundStation5 Star10) 52.02)
	(= (slew_time Star10 Star6) 0.8335)
	(= (slew_time Star6 Star10) 0.8335)
	(= (slew_time Star10 GroundStation7) 29.22)
	(= (slew_time GroundStation7 Star10) 29.22)
	(= (slew_time Star10 Star8) 78.69)
	(= (slew_time Star8 Star10) 78.69)
	(= (slew_time Star10 Star9) 23.11)
	(= (slew_time Star9 Star10) 23.11)
	(= (slew_time Star11 GroundStation0) 91.3)
	(= (slew_time GroundStation0 Star11) 91.3)
	(= (slew_time Star11 Star1) 45.91)
	(= (slew_time Star1 Star11) 45.91)
	(= (slew_time Star11 GroundStation2) 19.38)
	(= (slew_time GroundStation2 Star11) 19.38)
	(= (slew_time Star11 Star3) 9.796)
	(= (slew_time Star3 Star11) 9.796)
	(= (slew_time Star11 GroundStation4) 61.01)
	(= (slew_time GroundStation4 Star11) 61.01)
	(= (slew_time Star11 GroundStation5) 1.81)
	(= (slew_time GroundStation5 Star11) 1.81)
	(= (slew_time Star11 Star6) 23.56)
	(= (slew_time Star6 Star11) 23.56)
	(= (slew_time Star11 GroundStation7) 36.38)
	(= (slew_time GroundStation7 Star11) 36.38)
	(= (slew_time Star11 Star8) 7.175)
	(= (slew_time Star8 Star11) 7.175)
	(= (slew_time Star11 Star9) 6.517)
	(= (slew_time Star9 Star11) 6.517)
	(= (slew_time Star11 Star10) 11.26)
	(= (slew_time Star10 Star11) 11.26)
	(= (data-stored) 0)
	(= (fuel-used) 0)
)
(:goal (and
	(pointing satellite0 Star6)
	(pointing satellite1 Star1)
	(pointing satellite2 Star3)
	(pointing satellite5 Star8)
	(pointing satellite6 Star11)
	(pointing satellite8 GroundStation5)
	(pointing satellite9 Star8)
	(have_image Star10 image3)
))
(:metric minimize (fuel-used))

)
